apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  system: ${{values.system | dump}}
  type:  ${{values.type | dump}}
  lifecycle: ${{values.lifecycle | dump}}
  owner:  ${{values.owner | dump}}
metadata:
  name: ${{values.component_id | dump}}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
    argocd/app-name: ${{values.component_id}}
    backstage.io/kubernetes-id: ${{values.component_id | dump}}
  tags:
    - golang
    - ${{ values.type | dump}}
    - ${{ values.lifecycle | dump}}
  links:
    - url: https://${{values.component_id}}.backstage.roxs.dev
      title: Website
      icon: Website